packages:
    - packages/*
    - apps/*
    - apps/workers/*

onlyBuiltDependencies:
    - "@clerk/shared"
    - "@swc/core"
    - cbor-extract
    - esbuild
    - sharp
    - unrs-resolver
    - workerd
